services:
  - type: web
    name: project-camp-api
    runtime: node
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /api/v1/healthcheck/
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: ACCESS_TOKEN_EXPIRY
        value: 15m
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_EXPIRY
        value: 7d
      - key: SERVER_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: MAILTRAP_SMTP_HOST
        sync: false
      - key: MAILTRAP_SMTP_PORT
        value: 2525
      - key: MAILTRAP_SMTP_USER
        sync: false
      - key: MAILTRAP_SMTP_PASS
        sync: false
      - key: FORGOT_PASSWORD_REDIRECT_URL
        sync: false
